# Homebrew formula for zarlcode
#
# Generated by tools/genformula.
# Users install with:
#   brew install zarldev/tap/zarlcode

class Zarlcode < Formula
  desc "Terminal coding agent / TUI — plan first, execute second, rewind anytime"
  homepage "https://github.com/zarldev/zarlmono"
  version "0.19.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.19.0/zarlcode_v0.19.0_darwin_arm64.tar.gz"
      sha256 "381dce72a19c13f701aa8af4d2f115fb410198ebf7ce24f17905e300655311a1"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.19.0/zarlcode_v0.19.0_darwin_amd64.tar.gz"
      sha256 "9425ca5fc52f537b67813c45ca19aaab6e40c22ea6915ca7e2d6e01cf8811a28"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.19.0/zarlcode_v0.19.0_linux_arm64.tar.gz"
      sha256 "593ed6157d96c279c13210a285740b0c530f28ad77d41bea49f537ebda1cc9d3"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.19.0/zarlcode_v0.19.0_linux_amd64.tar.gz"
      sha256 "1380637c60132ed008c832f698fcd0da0329e0ab308d36a79c6cbfc4082a2aae"
    end
  end

  def install
    bin.install "zarlcode"
  end

  test do
    system "#{bin}/zarlcode", "-version"
  end
end
