# Homebrew formula for zarlcode
#
# Generated by tools/genformula.
# Users install with:
#   brew install zarldev/tap/zarlcode

class Zarlcode < Formula
  desc "Terminal coding agent / TUI — plan first, execute second, rewind anytime"
  homepage "https://github.com/zarldev/zarlmono"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.4.0/zarlcode_v0.4.0_darwin_arm64.tar.gz"
      sha256 "55f8e397bdf14edd577ac45266a6edb757dd37bed912c17be1b5862bc2185a34"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.4.0/zarlcode_v0.4.0_darwin_amd64.tar.gz"
      sha256 "195f8a5aae9e12810cb038f21af401302b9517f3acaeac67dc3335c27ae60642"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.4.0/zarlcode_v0.4.0_linux_arm64.tar.gz"
      sha256 "3bb39bfd2c00bcee8be7af6a4a8abc04c4d3bd10a2195f1c8ab19e4da4c80355"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.4.0/zarlcode_v0.4.0_linux_amd64.tar.gz"
      sha256 "57a3bc1a15417d2b6ccf8c70cc73a12463184b7cc1cd80480334b14a5183580a"
    end
  end

  def install
    bin.install "zarlcode"
  end

  test do
    system "#{bin}/zarlcode", "-version"
  end
end
