# Homebrew formula for zarlcode
#
# Generated by tools/genformula.
# Users install with:
#   brew install zarldev/tap/zarlcode

class Zarlcode < Formula
  desc "Terminal coding agent / TUI — plan first, execute second, rewind anytime"
  homepage "https://github.com/zarldev/zarlmono"
  version "0.15.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.15.0/zarlcode_v0.15.0_darwin_arm64.tar.gz"
      sha256 "9eaf0678bb8e03572f4706d586da09ca2f3af1e9f3d4fbcbe7a8d6f02bac6aaa"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.15.0/zarlcode_v0.15.0_darwin_amd64.tar.gz"
      sha256 "3033cb2b04816a0e7e33936c7bd1b001dc7faed6bdb079596022c07585debfc6"
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.15.0/zarlcode_v0.15.0_linux_arm64.tar.gz"
      sha256 "bdc54e761cd8c8492e798fa8f23b02bfe4d9737c9205d328d1bd0fa81469eb0c"
    else
      url "https://github.com/zarldev/zarlmono/releases/download/zarlcode/v0.15.0/zarlcode_v0.15.0_linux_amd64.tar.gz"
      sha256 "5d934335c9cefe81853aa0871a4583d38039dda43cb334381d4585d18510b265"
    end
  end

  def install
    bin.install "zarlcode"
  end

  test do
    system "#{bin}/zarlcode", "-version"
  end
end
